### ISSUE TITLE
(wish) Sort all lines if no selection

### ISSUE THREAD

**Issue by kvichans** [CudaText-addons/cuda_sort#1]

**Comment by Alexey-T** [comment]
Upd. gh only. See readme (option sort_all=1)
ok?

**Comment by kvichans** [comment]
Еще не автоматом беру с ГХ
Нужно подать 
  https://github.com/CudaText-addons/cuda_sort
в плагин "Уст с ГХ". Так?

**Comment by kvichans** [comment]
сработало

**Comment by Alexey-T** [comment]
да, решено?

**Comment by kvichans** [comment]
спасибо
