### ISSUE TITLE
(wish) Use vert.selection

### ISSUE THREAD

**Issue by kvichans** [CudaText-addons/cuda_sort#2]
1) Если вызваны функции прямого действия, то использовать вертикальное выделение для неявного учета позиций **от** и **до**.
В частности, при нулевой ширине выделения - ничего не изменять.

2) Если вызван диалог, то заполнять поля **от** и **до** по вертикальному выделению.
В частности, при нулевой ширине выделения - заполнять оба поля одинаковым значением

**Comment by Alexey-T** [comment]
Okey wish

**Comment by Alexey-T** [comment]
2 Решено, в ГХ

**Comment by kvichans** [comment]
2) Нет! Не решено
Такая ситуация возникала уже много раз. Визуально вертикальное выделение и выделение с помощью нескольких кареток могут не отличаться. Нужно ловить такие случаи и работать с ними одинаково. Иначе пользователи (пока в моем лице) офигивают: они видят вертикальное выделение, а Куд его не использует. То, что Куд учитывает **способ** получения этого выделения, это проблема не пользователей, а Куд.

**Comment by Alexey-T** [comment]
почти верно.Дайте пач для ф-ции get_offsets()

**Comment by kvichans** [comment]
я? патч? для функции? это выше моих возможностей

**Comment by kvichans** [comment]
Нужно решать на уровне ядра. Масса ситуаций, когда ядро учитывает предысторию положения:
- эти каретки "верт.выделение"
- эти каретки "выделение каретками"

А пользователь разницы не видит и она ему мешает

**Comment by kvichans** [comment]
Желательно иметь на уроне ядра запрос: "текущее выделение можно назвать вертикальным? Если да, то какие у него опорные точки?"

**Comment by kvichans** [comment]
И **ядро** и **плагины** перед обработкой того, что они подозревают в "верт.выделенности" должны обращаться к этому запросу.

**Comment by Alexey-T** [comment]
"нужн на уровне ядра решать".Это пока выше возможностей

**Comment by CudaText-addons** [comment]
Насчет 1). Тут неудобно будет мне, учет колонок неявно

**Comment by kvichans** [comment]
Осталось не понято: что изменилось?

**Comment by Alexey-T** [comment]
пока нет изменения. Делать 1) не хочу.

**Comment by kvichans** [comment]
Уже яснее.
Ждем 2)
